# Generated by Django 2.2 on 2019-04-07 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(to='core.Category'),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.ManyToManyField(to='core.Service'),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
