# Generated by Django 2.2 on 2019-04-08 12:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190407_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.business_image_file_path),
        ),
    ]
